# Generated by Django 5.1.4 on 2024-12-26 09:48

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")
    for row in User.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["psrn"])



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_id_user_is_librarian_user_psrn'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
