# Generated by Django 5.1.4 on 2024-12-26 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20241226_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='psrn',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True,
                                   serialize=False, unique=True),
        ),
    ]
