# Generated by Django 5.1.4 on 2024-12-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0002_issuinghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssuingHistory',
        ),
    ]
