# Generated by Django 5.1.4 on 2024-12-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0002_remove_genre_genre_name_case_insensitive_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_date'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
