# Generated by Django 5.1.4 on 2024-12-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0004_librarysettings_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='total_late_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
