# Generated by Django 5.1.4 on 2024-12-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0006_borrowinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='MEDIA_ROOT/covers/'),
        ),
    ]
