# Generated by Django 5.1.4 on 2024-12-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0010_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowinghistory',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowinghistory',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='borrowinghistory',
            name='bookinst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_catalog.bookinstance'),
        ),
    ]
