# Generated by Django 5.1.4 on 2024-12-29 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0011_remove_borrowinghistory_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='borrowed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrowinghistory',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
