# Generated by Django 5.1.4 on 2024-12-29 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0012_alter_borrowinghistory_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowinghistory',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_catalog.book'),
        ),
    ]
