# Generated by Django 5.1.4 on 2024-12-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0013_borrowinghistory_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowinghistory',
            name='book',
        ),
    ]
