# Generated by Django 5.1.4 on 2024-12-29 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0014_remove_borrowinghistory_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowers',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
