# Generated by Django 5.1.4 on 2025-01-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0016_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
