# Generated by Django 5.1.4 on 2025-01-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0018_portalfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
