# Generated by Django 5.1.4 on 2025-01-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0020_bookrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.IntegerField(blank=True, help_text='Year of publication', null=True),
        ),
    ]
